# Model configuration
# name|HuggingFace repository|GGUF filename|model directory

Qwen2.5-Coder-7B-Abliterated|bartowski/Qwen2.5-Coder-7B-Instruct-abliterated-GGUF|Qwen2.5-Coder-7B-Instruct-abliterated-Q4_K_M.gguf|Qwen2.5-Coder-7B
Qwen3.5-4B-Super-Coder|jica98/qwen3.5-4B-super-coder|qwen3.5-4B-super-coder.Q4_0.gguf|Qwen3.5-4B-Super-Coder
Gemma-4-E4B-it|google/gemma-4-E4B-it|gemma-4-E4B-it-Q4_0.gguf|Gemma-4-E4B-it
Gemma-4-E2B-it|google/gemma-4-E2B-it|gemma-4-E2B-it-Q4_0.gguf|Gemma-4-E2B-it
Qwen2.5-Coder-3B|bartowski/Qwen2.5-Coder-3B-Instruct-GGUF|Qwen2.5-Coder-3B-Instruct-Q4_K_M.gguf|Qwen2.5-Coder-3B
